Add Dockerfile
AlDevCR/local_match pull request #15
Opened 2019-01-03 15:24 UTC by pabgo

This file builds a docker container based on Ubuntu 18.04 with Qt 5.12.0,CMake and other tools

2019-01-03 19:53 UTC, wfallascr requested changes

2019-01-03 19:53 UTC, wfallascr commented on Dockerfile
> +    #&& echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
Clean up commented commands

2019-01-03 20:21 UTC, luvalverde requested changes

2019-01-03 20:21 UTC, luvalverde commented on Dockerfile
> +#RUN cd $QT_BASE_DIR && make clean \
why is it commented?

2019-01-04 15:24 UTC, pabgo commented
PR back to you @wfallascr @luvalverde

2019-01-04 15:28 UTC, luvalverde approved these changes
Looks ok for me, just squash your commits @pabgo

2019-01-07 14:08 UTC, wfallascr approved these changes

2019-01-07 14:08 UTC, merged