Add interface to manage events
AlDevCR/local_match pull request #16
Opened 2019-01-04 21:04 UTC by masolano

Add new interface to manage events and change visible status of the group box depends of type of user

2019-01-11 14:51 UTC, luvalverde requested changes

2019-01-11 14:51 UTC, luvalverde commented on localMatchApp/headers/homewindow.h
> +     * The function when the user click the button of new image is declare
... is declared

2019-01-11 15:22 UTC, masolano commented
PR back to you

2019-01-11 20:02 UTC, luvalverde approved these changes

2019-01-11 20:04 UTC, wfallascr requested changes

2019-01-11 20:04 UTC, wfallascr commented on localMatchApp/sources/homewindow.cpp
> +    if ( typeUser == 1 ) {
Please, contemplate the option of using an enum class for this.

2019-01-11 20:42 UTC, masolano commented
PR back to you

2019-01-14 14:30 UTC, wfallascr approved these changes

2019-01-14 14:30 UTC, merged