Delete config options in Qt build
AlDevCR/local_match pull request #17
Opened 2019-01-11 17:20 UTC by pabgo

Delete configuration options to build Qt. These changes were made to run CMake properly and fix undefined references while CMake is linking libraring during the built of the project.

2019-01-11 20:00 UTC, luvalverde requested changes

2019-01-11 20:00 UTC, luvalverde commented on Dockerfile
> +#RUN cd $QT_BASE_DIR && make clean \
you should learn from past mistakes

2019-01-11 20:06 UTC, wfallascr commented
It's time to to to to to to to to squasssshhh

2019-01-11 20:06 UTC, pabgo commented on Dockerfile
> +#RUN cd $QT_BASE_DIR && make clean \
I beg your pardon, master @luvalverde

2019-01-14 14:32 UTC, wfallascr approved these changes

2019-01-14 14:40 UTC, luvalverde approved these changes

2019-01-14 14:41 UTC, merged