Create new project with the user interface
AlDevCR/local_match pull request #3
Opened 2018-12-06 17:30 UTC by masolano

Create new project of LocalMatch of the user interface with the login interface, signup interface and main interface.

2018-12-06 19:32 UTC, luvalverde requested changes
I added some comments.
Also, let's use vectored images instead of .png or jpg.

https://vimm.com/what-is-a-vector-image/

Also:
- the image name "event1.jpg" is not very representative
- Why are there 2 same images ("logo.png") just differing in their size? The image must adjust to its corresponding container size.

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/mainwindow.cpp
> +    this->setFixedWidth(500);
do not use magic numbers

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/mainwindow.cpp
> +    QPixmap pix ("/home/marcelino/Desktop/LocalMatch/images/logo.png");
do not use hardcoded paths

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/mainwindow.cpp
> +void MainWindow::on_buttonSignUp_clicked()
According with the coding standard, underscores must never be used in an identifier.
Please apply this comment in all your files

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/mainwindow.cpp
> +    //if(ui->lineEditUser->text()=="marcelino" && ui->lineEditPassword->text()=="123"){
let's avoid to merge into master code that is commented or not being used

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/signup.cpp
> +SignUp::SignUp(QWidget *parent) :
according with the coding standard, function identifiers must have identifier names that begin with lowercase letters. Also, arguments whose input value is used by the function, and whose value is not changed by the function should be prefixed by "i_" (i.e. input).  

Please apply this comment in all your files.

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/signup.cpp
> +    this->setFixedWidth(500);
avoid magical numbers

2018-12-06 19:32 UTC, luvalverde commented on localMatchApp/signup.cpp
> +    QPixmap pix ("/home/marcelino/Desktop/LocalMatch/images/logo.png");
let's use relative paths

2018-12-06 19:42 UTC, luvalverde commented
Like this will be the base of the project, would be useful to define directories to separate:

header files -> headers
source code -> src
tests ->test
so, the following code will be located in an standard place

2018-12-07 15:35 UTC, luvalverde commented on localMatchApp/mainwindow.cpp
> +void MainWindow::on_buttonSignUp_clicked()
Check out this link:
http://doc.qt.io/qt-5/designer-using-a-ui-file.html

2018-12-07 16:35 UTC, wfallascr requested changes

2018-12-07 16:35 UTC, wfallascr commented on localMatchApp/signup.cpp
> +    QMessageBox* msgbox = new QMessageBox(this);
Memory leak. Please, contemplate the option of using smart pointers here or any other RAII approach.

2018-12-07 19:19 UTC, masolano commented on localMatchApp/mainwindow.cpp
> +    this->setFixedWidth(500);
Done

2018-12-07 19:20 UTC, masolano commented on localMatchApp/mainwindow.cpp
> +    QPixmap pix ("/home/marcelino/Desktop/LocalMatch/images/logo.png");
@Done

2018-12-07 20:47 UTC, luvalverde requested changes
Some comments

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/headers/homewindow.h
> +    explicit HomeWindow(QWidget *parent = nullptr);
i_parent

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/headers/mainwindow.h
> +    explicit MainWindow(QWidget *parent = 0);
i_parent

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/sources/homewindow.cpp
> +    int widthSizeLogo = 150;
check the coding standard for Magical Numbers

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/sources/mainwindow.cpp
> +    int fixedWidthMainWindow = 500;
check the coding standard for Magical Numbers

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/sources/mainwindow.cpp
> +    if(ui->lineEditUser->text()=="masolano" && ui->lineEditPassword->text()=="123"){
Add a comment for these hardcoded values.
Add a TODO comment indicating this must be changed.

2018-12-07 20:47 UTC, luvalverde commented on localMatchApp/sources/signup.cpp
> +    int fixedWidthSignUpWindow = 500;
check the coding standard for Magical Numbers

2018-12-10 15:32 UTC, luvalverde requested changes
I added some comments

2018-12-10 15:32 UTC, luvalverde commented on localMatchApp/LocalMatch.pro.user
> +    <value type="QString" key="ProjectExplorer.BuildConfiguration.BuildDirectory">/home/marcelino/Desktop/build-LocalMatch-Desktop-Debug</value>
this seems to be hard-coded to @masolano computer
Let's take a look at this
http://doc.qt.io/qtcreator/creator-sharing-project-settings.html

2018-12-10 15:32 UTC, luvalverde commented on localMatchApp/LocalMatch.pro.user.3.2-pre1
> +    <value type="QString" key="ProjectExplorer.BuildConfiguration.BuildDirectory">/home/andres/build-LocalMatch-Desktop-Debug</value>
this seems to be hard-coded to @anpineda computer

2018-12-10 15:32 UTC, luvalverde commented on localMatchApp/sources/homewindow.cpp
> +    ui->labelDescription->setText("So perhaps, you've generated some fancy text, and you're content that you can now copy and paste your fancy text in the comments section of funny cat videos, but pe
according with the coding standard, the maximum recommended length of a line of code including white-space is 80 characters.

2018-12-10 16:25 UTC, masolano commented
PR back to you

2018-12-10 19:14 UTC, wfallascr requested changes

2018-12-10 19:14 UTC, wfallascr commented on localMatchApp/sources/homewindow.cpp
> +    ui->labelNameUser->setText("Marcelino Solano");
Why this value?

2018-12-10 19:14 UTC, wfallascr commented on localMatchApp/headers/signup.h
> +}
Please, add doxygen documentation of all your classes/functions

2018-12-10 20:54 UTC, masolano commented
PR back to you

2018-12-11 15:32 UTC, luvalverde requested changes
Just minor comments.
Please squash your commits

2018-12-11 15:32 UTC, luvalverde commented on localMatchApp/sources/homewindow.cpp
> + * In this function its created what is necessary
In this function is created ...

2018-12-11 15:32 UTC, luvalverde commented on localMatchApp/sources/mainwindow.cpp
> + * In this function its created what is necessary to
In this function is created ...

2018-12-11 15:32 UTC, luvalverde commented on localMatchApp/sources/signup.cpp
> + * In this function its created what is necessary to build
In this function is created ...

2018-12-11 16:33 UTC, masolano commented
PR back to you

2018-12-11 16:49 UTC, wfallascr approved these changes

2018-12-11 16:49 UTC, luvalverde approved these changes
Nice

2018-12-11 16:49 UTC, merged